# Generated by Django 3.2.9 on 2021-12-04 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeju', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='telephone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{0,4}-?\\d{3,4}-?\\d{4}$', message='전화번호를 입력해 주세요.')]),
        ),
    ]
