# Generated by Django 3.2.9 on 2021-12-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeju', '0004_alter_tour_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='photo',
        ),
    ]
