# Generated by Django 3.2.9 on 2021-12-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_rename_phote_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
