# Generated by Django 3.2.9 on 2021-11-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('genre', models.CharField(max_length=100, verbose_name='장르')),
                ('episodes', models.IntegerField(verbose_name='회차')),
                ('country', models.CharField(max_length=100, verbose_name='국가')),
                ('english', models.BooleanField(verbose_name='영어를 하는가?')),
            ],
        ),
    ]
