# Generated by Django 3.2.9 on 2021-11-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Netflix',
        ),
    ]
