# Generated by Django 3.2.9 on 2021-11-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='국가')),
                ('city', models.CharField(max_length=100, verbose_name='도시')),
                ('day_to_go', models.DateField(verbose_name='가는 날')),
                ('day_to_come', models.DateField(verbose_name='오는 날')),
            ],
        ),
    ]
