# Generated by Django 3.2.9 on 2021-11-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='check1',
            field=models.BooleanField(default=1, verbose_name='항공권'),
            preserve_default=False,
        ),
    ]
