# Generated by Django 3.2.9 on 2021-11-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0004_travel_check1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='check1',
        ),
    ]
